### ISSUE TITLE
Support Single Packet Authorization with Port Randomization

### ISSUE THREAD

**Issue by solhuebner** [oneru/Fwknop2#16]
Can you please add an option to support a scenario like in https://www.cipherdyne.org/blog/2008/06/single-packet-authorization-with-port-randomization.html

So that the destination port is random between 10000-65535.

Kind regards

**Comment by oneru** [comment]
This should be quite easy to get working. Thanks for the suggestion.

**Comment by solhuebner** [comment]
Great :-)

Thank you for considering it!

**Comment by oneru** [comment]
This feature will be available in 1.1, which should be ready in a couple weeks or so.
