### ISSUE TITLE
--nat-local support

### ISSUE THREAD

**Issue by kitrule** [oneru/Fwknop2#22]
Please could you add support for --nat-local.

It's similar to the existing "NAT Access" option you have under "Message Type" except the nat rules fwknopd create redirect traffic to the system fwknopd is on, so it doesn't require a separate ip address to be specified.

Many thanks.

**Comment by oneru** [comment]
I just uploaded a beta client that has support for nat-local.  If you would like to opt into beta to help test, the link is https://play.google.com/apps/testing/org.cipherdyne.fwknop2

**Comment by kitrule** [comment]
Hi, thanks for working on this. I've opted in to the beta and just done some testing, it seems the beta version isn't sending SPA packets at all. I've just reported the crash it generated through the "Unfortunately, Fwknop2 has stopped" dialogue and I've also now tried uninstalling and reinstalling and it still produces a crash when tapping on "send knock". It doesn't appear setting any of the options for message type, allow IP or SSH app prevent the crash.

**Comment by oneru** [comment]
The crash report shows an unexpected error: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "srand" referenced by "libfwknop.so"

Some research suggests that this is an issue with using the more recent android NDK on a pre-lolipop device.  I'm attempting to recompile a fixed version.  I'll test it out on an ICS Android VM.  the next Beta update will hopefully fix the issue.

**Comment by oneru** [comment]
And after finding a crash bug in that build for everything *other* than nat-local, I've uploaded yet another build to beta that should be working properly.

**Comment by kitrule** [comment]
Hi, just tried latest update and submitted a new report on crash.

**Comment by oneru** [comment]
This has taken waaaaayyyyy too long to track down and fix, but I think the build I just pushed should fix your crash, and also have nat-local support.  Once this update is in the play store, hopefully it should be working.  BTW, I blame google for this one.  I have dived deep in the land of the not-well-documented, and hopefully found the fix.

**Comment by kitrule** [comment]
Yup, that fixed it. Thanks!

**Comment by kitrule** [comment]
Sorry, I closed this too soon. I just realised in the fwknopd logs that the rules it is generating from the android SPA packets are in the wrong chains, e.g.

SPA from android:
Dec 01 23:45:34 SERVER fwknopd[21954]: Added FORWARD rule to FWKNOP_FORWARD for x.x.x.x -> y.y.y.y tcp/zzzz, expires at 1449013594
Note: This rule also specifies a destination as the internet side IP (y.y.y.y) although the server is behind a nat firewall with a different IP address on its local network.

SPA from linux:
Dec 01 23:47:37 SERVER fwknopd[21954]: Added local NAT rule to FWKNOP_INPUT for x.x.x.x -> 0.0.0.0/0 tcp/zzzz, expires at 1449013672

**Comment by kitrule** [comment]
Seems to be a bug in fwknop (2.6.7) that I will report there and try link/report back.

To summarise, I enabled debug logging on fwknopd and found that it will add rules to the forward chain instead of the input chain whenever it gets SPA message type 6 (Client timeout local NAT access msg) or message type 2 (NAT access msg).

It seems message type 6 is used whenever a timeout is specified greater than 0 and message type 2 is used whenever a timeout of 0 is specified.

Both message types also logged "forward_access_rule() forward_all: 0, nat_ip: z.z.z.z, nat_port: 22" after the SPA field values from fwknopd.

On linux my .fwknoprc stanza omitted FW_TIMEOUT entirely, producing SPA message type 5 (Local NAT access msg) with resulting rules in the correct chain.

**Comment by oneru** [comment]
I would like to get Michael Rash's opinion on this as well. We'll figure out what is going on, and which is the correct behavior.  Thanks for your investigation on this.

**Comment by oneru** [comment]
@kitrule This issue should be fixed in fwknop2-beta and the fwknop 2.6.8 release.  Could you confirm?

**Comment by kitrule** [comment]
Yup, that did it. Thank you!

**Comment by oneru** [comment]
Fixed with release of 1.2.0.
