### ISSUE TITLE
Feature Request: OpenVPN

### ISSUE THREAD

**Issue by Joeviocoe** [oneru/Fwknop2#25]
Knocking, then opening JuiceSSH is nice,.... but knocking, then opening up OpenVPN is also very nice.

I don't SSH from the outside, but I would if I am VPN'ing first.

**Comment by oneru** [comment]
This would be useful, I'll try to get it working.

**Comment by oneru** [comment]
I uploaded a beta that contains support for launching a saved OpenVPN for Android config.  This will eventually be released as stable, but if you want to opt into the beta to get a sneak peek and help test it out, you can do so at https://play.google.com/apps/testing/org.cipherdyne.fwknop2

**Comment by oneru** [comment]
Fixed with release of 1.2.0
