### ISSUE TITLE
Failure to run Juicessh as external app on Nexus 7

### ISSUE THREAD

**Issue by truckershitch** [oneru/Fwknop2#33]
Trying to run Juicessh as external app on Nexus 7 gives this message:
"Fwknop2 does not have permission to access Juicessh connection list.  Please reinstall Fwknop2."

**Comment by oneru** [comment]
@truckershitch I believe this is the new permissions system in Android m. A real fix is coming in the next version of Fwknop2, but You can work around the issue by going to Android settings->apps->fwknop2->permissions, and enabling permissions there.

**Comment by truckershitch** [comment]
Thanks, that did the trick!
