### ISSUE TITLE
when Resolve IP is used, not packet is sent

### ISSUE THREAD

**Issue by rabin-io** [oneru/Fwknop2#5]
The resolve IP is not working for me,
only when i change the `Allow IP` to set the IP manually, i see the packet arrive in the firewall.

**Comment by oneru** [comment]
@rabin-io Can you access this url? http://whatismyip.akamai.com/ I wonder if the http connection to akamai to get the ip was blocked or failed due to network problems.
Would it be possible for you to capture an adb log of an attempt using resolve ip?

**Comment by rabin-io** [comment]
@oneru, Thanks, seems like AdAway (on Android) and uBlock on Firefox/Desktop block this url for some reason.

**Comment by oneru** [comment]
@rabin-io Ah-hah, good to know. I have added the dns based ip resolution back to the app, which fails through to akamai, so this shouldn't be an issue for the final release. I already intend to add options to customize this in v1.1.

**Comment by rabin-io** [comment]
@oneru , you should also display some notification/message in case the IP resolving failed.
