### ISSUE TITLE
Check for base64 validity

### ISSUE THREAD

**Issue by mrash** [oneru/Fwknop2#7]
When checking the either of the "is base64" boxes, it would be handy if a verification step would make sure the supplied data only contains characters allowed within the base64 encoding character set, and also that the trailing '=' padding chars match the multiple of four requirement.

**Comment by oneru** [comment]
@mrash  So with the "=" chars, the base64 keys should be a length that is a multiple of 4? And then the allowed chars are "a-z A-Z 0-9 +/", plus the "=" for padding? I considered adding a base64 validity test, but thought there was more to it than that. I can check for those two rules quite easily.

**Comment by mrash** [comment]
Those are the only two rules that I'm aware of, yes. There is something around the length of data and embedded newlines, and so it would be good to test the client with base64 data that is up to the full allowed length. I'll test this.

**Comment by oneru** [comment]
@mrash If you find another limitation on the base64 keys, just reopen.
